build.gradle
src/main/java/com/likelion/realtalk/global/common/response/ErrorResponse.java
src/main/java/com/likelion/realtalk/global/config/SwaggerConfig.java
src/main/java/com/likelion/realtalk/global/config/WebConfig.java
src/main/java/com/likelion/realtalk/global/exception/CustomException.java
src/main/java/com/likelion/realtalk/global/exception/ErrorCode.java
src/main/java/com/likelion/realtalk/global/exception/GlobalExceptionHandler.java
src/main/java/com/likelion/realtalk/global/security/config/SecurityConfig.java
src/main/java/com/likelion/realtalk/infra/claude/ClaudeAiClient.java
src/main/resources/application.yml

- feature/#1
📄  **작업한 내용**
- 프로젝트 기본 구조 설정
- config 파일 생성(swagger, security)
- 공통 에러 응답 객체 생성
- 예외처리 관련 클래스 생성(CustomException, ErrorCode, GlobalExceptionHandler)
- application.yml mysql 기본 설정
- 필요한 의존성들 추가하였습니다(security, OAuth2, Mysql)
- Resolved: #1
프로젝트 구조 적절한지 확인 부탁드립니다!

프로젝트 초기 설정 PR 입니다.

---

build.gradle
src/main/java/com/likelion/realtalk/global/config/RedisConfig.java
src/main/java/com/likelion/realtalk/infra/redis/docker-compose-redis.yml
src/main/resources/application.yml

- feature/#3
📄  **작업한 내용**
Redis 컨테이너 및 연결 기본 설정 추가
Redis 컨테이너로 띄우려면 네트워크 만들고 compose 해주셔야 합니다.
- Resolved: #3

chore: Redis 컨테이너 및 연결 설정 추가

---

.github/workflows/deploy.yml
src/main/java/com/likelion/realtalk/domain/auth/entity/Auth.java
src/main/java/com/likelion/realtalk/domain/auth/service/AuthService.java
src/main/java/com/likelion/realtalk/domain/common/BaseTime.java
src/main/java/com/likelion/realtalk/domain/oauth/handler/OAuth2LoginSuccessHandler.java
src/main/java/com/likelion/realtalk/domain/oauth/handler/OAuth2LogoutSuccessHandler.java
src/main/java/com/likelion/realtalk/domain/oauth/service/OAuth2UserService.java
src/main/java/com/likelion/realtalk/domain/user/entity/User.java
src/main/java/com/likelion/realtalk/domain/user/entity/UserProfile.java
src/main/java/com/likelion/realtalk/global/config/SwaggerConfig.java
src/main/java/com/likelion/realtalk/global/security/config/SecurityConfig.java
src/main/java/com/likelion/realtalk/global/security/jwt/JwtTokenFilter.java
src/main/resources/application.yml

- feature/#16
📄  **작업한 내용**
- CORS 설정
- SwaggerConfig
- 엔티티 생성자에 protected 적용, 빌더와 정적 팩토리 메서드 사용하게 리팩토링
- api 추가됨에 따라 swagger 추가 필요합니다!
- Resolved: #16

Chore/#16 CORS 및 Swagger 설정

---

src/main/java/com/likelion/realtalk/domain/auth/service/AuthService.java
src/main/java/com/likelion/realtalk/domain/oauth/handler/OAuth2LoginSuccessHandler.java
src/main/java/com/likelion/realtalk/domain/oauth/handler/OAuth2LogoutSuccessHandler.java
src/main/java/com/likelion/realtalk/global/security/jwt/JwtCookieUtil.java

- fix/#33
📄  **작업한 내용**
- jwt 토큰 samesite 설정
- realtalks.co.kr 의 도메인에 쿠키 들어가게 설정했습니다.
- Resolved: #33

Fix/#33 jwt 토큰 samesite 설정

---

src/main/java/com/likelion/realtalk/global/config/WebConfig.java

fix: 웹소켓 cors 허용 엔드포인트 추가

---

src/main/java/com/likelion/realtalk/domain/oauth/handler/OAuth2LoginSuccessHandler.java

- fix/token-issue
📄  **작업한 내용**
- 토큰 발급 시 refresh token만 발급
- 이후 api에서 access token 발급
- Resolved: token-issue

fix: 로그인 시 refresh token만 쿠키에 저장

---

src/main/resources/application.yml

fix: application.yml 로그 수집하도록 수정

---

src/main/java/com/likelion/realtalk/domain/debate/api/DebateController.java

fix: createRoom 엔드포인트 에러 수정

---

deploy/deploy-single.sh

fix: 외부 파일에서 key json 받아오기 - sh 수정

---

deploy/deploy-single.sh
src/main/resources/application.yml

fix: 외부 파일에서 key json 받아오기 - sh 수정2

---

deploy/deploy-single.sh

fix: 외부 파일에서 key json 받아오기 - sh 수정3

---

src/main/java/com/likelion/realtalk/domain/debate/dto/DebateRoomResponse.java

- private Long createUserId;
DebateRoomResponse 에 방 생성자 필드 추가

chore: DebateRoomResponse 에 방 생성자 필드 추가

---

src/main/java/com/likelion/realtalk/domain/debate/service/DebateRoomService.java

📄  **작업한 내용**
chore: 방 정보 조회 api / 반환값 createUserId 추가

chore: 방 정보 조회 api / 반환값 createUserId 추가

---

.github/workflows/deploy.yml
deploy/deploy-single.sh

fix: 배포 스크립트 수정

---

deploy/deploy-single.sh

호스트 경로의 파일을 도커가 못 읽어오는 상황이라,
도커 볼륨을 임의로 만들어 그 볼륨 안의 key를 읽어오게 하였습니다..

fix: 배포 스크립트 수정 - docker volume 도입

---

src/main/java/com/likelion/realtalk/domain/debate/api/SideStatsController.java
src/main/java/com/likelion/realtalk/domain/debate/dto/SideStatsDto.java
src/main/java/com/likelion/realtalk/domain/debate/dto/SideStatsRequest.java
src/main/java/com/likelion/realtalk/domain/debate/service/SideStatsService.java
src/main/resources/static/debateroom.html
src/main/resources/static/participants.html

- renderAllParticipants 함수에서 AUDIENCE 기준 계산을 제거하고 SPEAKER + AUDIENCE 통합 기준으로 Side A/B 퍼센트 계산하도록 변경
- 각 Room 카드에 게이지 바와 A/B 비율 표시 추가
- UI 스타일 보강 (게이지, 라벨, 카드 디자인)
- escapeHtml 적용으로 제목 출력 시 XSS 방지
- feature/#99
📄  **작업한 내용**
- Resolved: #99

feat(ui): 전체 Room 참여자 목록에 A/B 통합 퍼센트 게이지 추가

---

src/main/java/com/likelion/realtalk/domain/debate/dto/AiSummaryDto.java
src/main/java/com/likelion/realtalk/domain/debate/dto/DebateResultDto.java
src/main/java/com/likelion/realtalk/domain/debate/dto/SpeakerMessageDto.java
src/main/java/com/likelion/realtalk/domain/debate/entity/DebateResult.java
src/main/java/com/likelion/realtalk/domain/debate/repository/DebateResultRepository.java
src/main/java/com/likelion/realtalk/domain/debate/service/AiService.java
src/main/java/com/likelion/realtalk/domain/debate/service/DebateRedisService.java
src/main/java/com/likelion/realtalk/domain/debate/service/DebateResultService.java
src/main/java/com/likelion/realtalk/domain/debate/service/DebateRoomService.java

- feature/#107
📄  **작업한 내용**
AI 잘못된 response 반환 시 retry 로직 추가
토론 종료 시  debateResult에 정보 추가
- Resolved: #107

feat : AI 잘못된  response 반환 시 retry, 토론 종료 시 debateResult에 정보 추가

---

src/main/java/com/likelion/realtalk/domain/debate/service/RecordingService.java

녹음 시작시 side 값 프론트로 넘겨주도록 수정

---

src/main/java/com/likelion/realtalk/domain/debate/repository/DebateResultRepository.java

- hotfix/#115
📄  **작업한 내용**
- 토론 결과 조회 쿼리 오류 수정
- Resolved: #115

[Hotfix]토론 결과 조회 쿼리 오류 수정

---

src/main/java/com/likelion/realtalk/domain/debate/service/RecordingService.java

- hotfix/#115
📄  **작업한 내용**
서버에 토론 결과 조회 기능 반영
- Resolved: #115

서버에 토론 결과 조회 기능 반영

---

src/main/java/com/likelion/realtalk/domain/debate/dto/AiSummaryDto.java
src/main/java/com/likelion/realtalk/domain/debate/service/SpeakerService.java

- feature/#124
📄  **작업한 내용**
- AI 요약 response에 side 추가
- Resolved: #124

[Feature]AI 요약 response에 side 추가

---

src/main/resources/logback-spring.xml

- feature/#124
📄  **작업한 내용**
AI 요약 reponse Side 추가
- Resolved: #124

서버에 AI 요약 reponse Side 추가 반영
